# Generated by Django 4.1.1 on 2022-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuckNorrysJokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.URLField(blank=True, default='', max_length=255)),
                ('joke_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=255)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'chuck_norrys_jokes',
            },
        ),
        migrations.CreateModel(
            name='OwnJokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'own_jokes',
            },
        ),
    ]
